### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by Arnold1** [PuerkitoBio/goquery#145]
Hi, any idea whats causing this issue?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10d703]

goroutine 1 [running]:
panic(0x249280, 0xc42000c090)
  /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
golang.org/x/net/html.readAtLeastOneByte(0x0, 0x0, 0xc42024b000, 0x1000, 0x1000, 0xc420125b18, 0x68, 0x2b3fcf)
  /Users/arnold/tor_test/src/golang.org/x/net/html/token.go:299 +0x33
golang.org/x/net/html.(*Tokenizer).readByte(0xc4200741a0, 0x70)
  /Users/arnold/tor_test/src/golang.org/x/net/html/token.go:273 +0x265
golang.org/x/net/html.(*Tokenizer).Next(0xc4200741a0, 0xc42005a380)
  /Users/arnold/tor_test/src/golang.org/x/net/html/token.go:980 +0x99
golang.org/x/net/html.(*parser).parse(0xc420286630, 0xc42005a380, 0xc4200741a0)
  /Users/arnold/tor_test/src/golang.org/x/net/html/parse.go:2001 +0xa9
golang.org/x/net/html.Parse(0x0, 0x0, 0xc420125d50, 0x0, 0x0)
  /Users/arnold/tor_test/src/golang.org/x/net/html/parse.go:2026 +0x10c
github.com/PuerkitoBio/goquery.NewDocumentFromReader(0x0, 0x0, 0x1a, 0xc420125d20, 0x0)
  /Users/arnold/tor_test/src/github.com/PuerkitoBio/goquery/type.go:49 +0x39
main.(*MyBot).Login(0xc420017110, 0x29167d, 0x7, 0x292f8c, 0x9, 0xc4200001a0, 0x0)
  /Users/arnold/tor_test/tor.go:150 +0x29e
main.ExampleScrape()
  /Users/arnold/tor_test/tor.go:301 +0xc2
main.main()
  /Users/arnold/tor_test/tor.go:326 +0x14

**Comment by Arnold1** [comment]
closed.
