### ISSUE TITLE
.Find  Error "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by mejinke** [PuerkitoBio/goquery#15]
``` javascript

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x459f16]

goroutine 5196 [running]:
github.com/PuerkitoBio/goquery.funcÂ·008(0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jinke/golang/src/github.com/PuerkitoBio/goquery/traversal.go:383 +0x46
github.com/PuerkitoBio/goquery.mapNodes(0xc2091358f0, 0x1, 0x1, 0x2afca5fda5f8, 0x0, ...)
        /Users/jinke/golang/src/github.com/PuerkitoBio/goquery/traversal.go:532 +0x8f
github.com/PuerkitoBio/goquery.findWithSelector(0xc2091358f0, 0x1, 0x1, 0x718dd0, 0x25, ...)
        /Users/jinke/golang/src/github.com/PuerkitoBio/goquery/traversal.go:389 +0x8d
github.com/PuerkitoBio/goquery.(*Selection).Find(0xc208006660, 0x718dd0, 0x25, 0xc2000b3000)
        /Users/jinke/golang/src/github.com/PuerkitoBio/goquery/traversal.go:27 +0x45
main.qiche4sListSpider(0xc2000aca40, 0x2, 0xc20487e400, 0x32, 0x1512, ...)
        /Users/jinke/golang/src/cds_spider/price/main/bitauto.go:195 +0x406
main.funcÂ·005(0x1, 0xc2007fe180)
        /Users/jinke/golang/src/cds_spider/price/main/bitauto.go:165 +0x20e
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc20125a480, 0x2afca5fdadb8, 0x25)
        /Users/jinke/golang/src/github.com/PuerkitoBio/goquery/iteration.go:7 +0xf7
main.qiche4sSpider(0xc2000aca40, 0x1447, 0x6b80f0, 0x0, 0x1512, ...)
        /Users/jinke/golang/src/cds_spider/price/main/bitauto.go:166 +0x5e5
main.funcÂ·008(0xc2000aca40, 0x1447, 0x6b80f0, 0x0, 0x1512, ...)
        /Users/jinke/golang/src/cds_spider/price/main/bitauto.go:263 +0xb6
created by cds_spider/price/frame.(*Frame).Start
        /Users/jinke/golang/src/cds_spider/price/frame/frame.go:116 +0x29c

```

code :

``` javascript
193  root, _ := html.Parse(res.Body)
194  document := goquery.NewDocumentFromNode(root)
195  selections := document.Find("div[class='lm_subprice_blc'] table tr")
196  if selections.Size() == 0 {
197         //.....
198         return
199  }
```

Will it be "root, _ := html.Parse(res.Body)" wrong here ?
update:

``` javascript
root, err := html.Parse(res.Body)
if err != nil {
//.......
 return
}
```

**Comment by avelino** [comment]
@PuerkitoBio example return error

```
doc, err := goquery.NewDocument("https://gist.githubusercontent.com/avelino/a4a8527f76d7eb14b2acb1e761c69b30/raw/98b1040bd1b5a09287b378f0327c37449ba0f5f5/test.html")
if err != nil {
    log.Println(err)
}
val, _ := doc.Find("meta[name=\"twitter:image\"]").Attr("content")
```
Error:
```
2016/04/30 03:48:40 unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x59657f]

goroutine 1 [running]:
panic(0x8f9ca0, 0xc82000e260)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
shelfgit.com/poorny/spider/providers/feeds.UnmarshalXML(0xc82013c150, 0x2c, 0xc82013c2d0, 0x29, 0xc82008c5a0, 0x118, 0x0, 0x0, 0x0, 0x0, ...)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/feeds/feeds.go:74 +0x5af
shelfgit.com/poorny/spider/providers.FeedByBot()
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/providers.go:173 +0xf35
shelfgit.com/poorny/spider/providers.Switch(0xc82000a5d0, 0x1, 0x1)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/providers/providers.go:107 +0x1466
main.main.func1(0xc820138000)
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/main.go:22 +0x103
github.com/codegangsta/cli.(*App).Run(0xc820134000, 0xc82000a5c0, 0x2, 0x2, 0x0, 0x0)
        /home/avelino/projects/go/src/github.com/codegangsta/cli/app.go:163 +0xbfc
main.main()
        /home/avelino/projects/go/src/shelfgit.com/poorny/spider/main.go:25 +0x163
exit status 2
```

**Comment by PuerkitoBio** [comment]
I ran the goquery-related code snippet, it works fine and returns `http://www.ovelhotarado.com/media/videos/tmb/11097/1.jpg` for `val`.

Please don't comment on old closed issues, open a new one instead - but first try to isolate the problem and make sure it is related to this project. From your panic's stacktrace, it looks like it happens in the poorny/spider/providersfeeds package, goquery doesn't appear in the trace. Make sure you check all errors.

HTH,
Martin
